despesas/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:id>', views.index, name='index'),
    path('view/', views.view, name='view'),
    path('saidas/', views.saidas, name='saidas'),
    path('entradas/', views.entradas, name='entradas'),
    path('notas/', views.notas, name='notas'),
    path('', views.paginainicial, name='paginainicial'),
     path('logout/', views.logout, name='logout'),
    
]

despesas/tarefas/urls.py
from django.contrib import admin
from django.urls import path, include

from register import views as register_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register_views.register, name="register"),
    path('', include('main.urls')),
    path('', include("django.contrib.auth.urls")),
]

despesas/main/models.py
from django.db import models
from django.contrib.auth.models import User

class Saida(models.Model):
    descricao = models.CharField(max_length=200)
    data = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Entrada(models.Model):
    descricao = models.CharField(max_length=200)
    data = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Nota(models.Model):
    titulo = models.CharField(max_length=200)
    conteudo = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

despesas/register/models.py
from django.db import models

# Create your models here.

despesas/main/forms.py
from django import forms
from .models import Saida, Entrada, Nota

class SaidaForm(forms.ModelForm):
    class Meta:
        model = Saida
        fields = ['descricao', 'data', 'valor']
        
class EntradaForm(forms.ModelForm):
   class Meta:
       model = Entrada
       fields = ['descricao', 'data', 'valor']
       
class HistoricoForm(forms.Form):
  entrada_form = EntradaForm()
  saida_form = SaidaForm()
  
class NotaForm(forms.ModelForm):
    class Meta:
        model = Nota
        fields = ['titulo', 'conteudo']
        
        

class FiltroForm(forms.Form):
    MES_CHOICES = [
        (1, 'Janeiro'),
        (2, 'Fevereiro'),
        (3, 'Março'),
        (4, 'Abril'),
        (5, 'Maio'),
        (6, 'Junho'),
        (7, 'Julho'),
        (8, 'Agosto'),
        (9, 'Setembro'),
        (10, 'Outubro'),
        (11, 'Novembro'),
        (12, 'Dezembro'),
    ]

    mes = forms.ChoiceField(choices=MES_CHOICES, label='Mês')
    ano = forms.IntegerField(required=False, label="Ano", widget=forms.NumberInput(attrs={'placeholder': 'Ano'}))
  

despesas/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

despesas/main/views.py
from django.shortcuts import render, redirect
from .forms import SaidaForm, EntradaForm, NotaForm, FiltroForm
from .models import Entrada, Saida, Nota
from django.contrib.auth.decorators import login_required
from django.db import models
from django.contrib.auth import logout as django_logout


def index(request, id):
    return render(request, 'main/index.html', {'id': id})

from django.shortcuts import render, redirect
from .forms import SaidaForm, EntradaForm
from .models import Entrada, Saida
from django.contrib.auth.decorators import login_required

@login_required
def entradas(request):
    if request.method == 'POST':
        form = EntradaForm(request.POST)
        if form.is_valid():
            entrada = form.save(commit=False)
            entrada.user = request.user
            entrada.save()
            return redirect('entradas')  # Redirecione para a página de entradas após o salvamento
    else:
        form = EntradaForm()

    entradas_salvas = Entrada.objects.filter(user=request.user)
    return render(request, 'main/entradas.html', {'form': form, 'entradas_salvas': entradas_salvas})

@login_required
def saidas(request):
    if request.method == 'POST':
        form = SaidaForm(request.POST)
        if form.is_valid():
            saida = form.save(commit=False)
            saida.user = request.user
            saida.save()
            return redirect('saidas')  # Redirecione para a página de saídas após o salvamento
    else:
        form = SaidaForm()

    saidas_salvas = Saida.objects.filter(user=request.user)
    return render(request, 'main/saidas.html', {'form': form, 'saidas_salvas': saidas_salvas})

@login_required
def view(request):
    # Obter entradas e saídas ordenadas por data
    entradas = Entrada.objects.filter(user=request.user).order_by('data')
    saidas = Saida.objects.filter(user=request.user).order_by('data')

    # Calcular os totais
    total_entradas = sum(entrada.valor for entrada in entradas)
    total_saidas = sum(saida.valor for saida in saidas)

    return render(request, 'main/view.html', {
        'entradas': entradas,
        'saidas': saidas,
        'total_entradas': total_entradas,
        'total_saidas': total_saidas,
    })

@login_required
def notas(request):
    if request.method == 'POST':
        form = NotaForm(request.POST)
        if form.is_valid():
            nota = form.save(commit=False)
            nota.user = request.user
            nota.save()
            return redirect('notas')  # Redirecione para a página de notas
    else:
        form = NotaForm()

    notas = Nota.objects.filter(user=request.user).order_by('-data_criacao')

    return render(request, 'main/home.html', {'form': form, 'notas': notas})

def paginainicial(request):
    return render(request, "main/paginainicial.html")


@login_required
def view(request):
    filtro_form = FiltroForm(request.GET)

    if filtro_form.is_valid():
        mes = filtro_form.cleaned_data['mes']
        ano = filtro_form.cleaned_data['ano']
        entradas = Entrada.objects.filter(user=request.user, data__month=mes, data__year=ano)
        saidas = Saida.objects.filter(user=request.user, data__month=mes, data__year=ano)
        total_entradas = entradas.aggregate(total_entradas=models.Sum('valor'))['total_entradas'] or 0
        total_saidas = saidas.aggregate(total_saidas=models.Sum('valor'))['total_saidas'] or 0
    else:
        entradas = Entrada.objects.filter(user=request.user)
        saidas = Saida.objects.filter(user=request.user)
        total_entradas = entradas.aggregate(total_entradas=models.Sum('valor'))['total_entradas'] or 0
        total_saidas = saidas.aggregate(total_saidas=models.Sum('valor'))['total_saidas'] or 0

    return render(request, 'main/view.html', {'entradas': entradas, 'saidas': saidas, 'total_entradas': total_entradas, 'total_saidas': total_saidas, 'filtro_form': filtro_form})
    
def logout(request):
    if request.method == 'POST' or request.method == 'GET':
        # Ações de logout
        django_logout(request)
        return redirect('login')


despesas/register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = RegisterForm()
    
    return render(request, "register/register.html",
                    {"form": form})



despesas/main/templates/main/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>{% block title %}Despesas{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#111;
			overflow-x: hidden;
			padding-top:20px;
		}    

		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			color: #818181;
			display:block;
		}  
  
        .sidenav a:hover{
			color:#f1f1f1;
		}     

        .main{
			margin-left:160px;
			padding: 0px 10px;
		}   
    </style>
</head>
 
<body>
	<div class="sidenav">
		<a href="/">Inicio</a>
		<a href="/notas">Notas</a>
		<a href="/view">Financeiro</a>
		<a href="/entradas">Entradas</a>
		<a href="/saidas">Saidas</a>
		<a href="/logout">Logout</a>
	</div>
 
	<div id="content" name="content" class="main">
		<div class="row justify-content-center">
			<div class="col-8">
				<hr class="mt-0 mb-4">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>
 
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

despesas/main/templates/main/entradas.html
{% extends "main/base.html" %}

{% block title %} Lista de Entradas {% endblock %}

{% block content %}
    <h1 class="mb-4">Entradas</h1>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center bg-secondary text-white">
            <h2 class="mb-0">Nova Entrada</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="#">
                {% csrf_token %}
                {% for entrada in lista.entrada_set.all %}
                    {% include "main/movimento_form.html" with movimento=entrada %}
                {% endfor %}

                <!-- Adicionar Entrada -->
                {% include "main/movimento_form.html" with movimento=None %}

                <!-- Salvar -->
                <button type="submit" name="save" value="save" class="btn btn-dark">
                    Salvar
                </button>
            </form>
        </div>
    </div>
{% endblock %}

despesas/main/templates/main/home.html
{% extends "main/base.html" %}

{% block title %} Notas {% endblock %}

{% block content %}
    <h1 class="mb-4">Suas Anotações</h1>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center bg-secondary text-white">
            <h2 class="mb-0">Nova Nota</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="#">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Nota</button>
            </form>
        </div>
    </div>

    <!-- Lista de Notas -->
    <div class="row">
        {% for nota in notas %}
            <div class="col-lg-4 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5>{{ nota.titulo }}</h5>
                    </div>
                    <div class="card-body">
                        <p>{{ nota.conteudo }}</p>
                        <p>Data de Criação: {{ nota.data_criacao }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

despesas/main/templates/main/movimento_form.html
<!-- movimento_form.html -->
<div class="input-group mb-3">
    <input type="text" value="{{ movimento.descricao }}" class="form-control" name="descricao{{ movimento.id }}" placeholder="Descrição">
    <input type="date" value="{{ movimento.data }}" class="form-control" name="data{{ movimento.id }}" placeholder="Data">
    <input type="text" pattern="[0-9]+(\.[0-9]{1,2})?" title="Informe um número válido" value="{{ movimento.valor }}" class="form-control" name="valor{{ movimento.id }}" placeholder="Valor">
</div>

despesas/main/templates/main/paginainicial.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial - Controle Financeiro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            text-align: center;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 1em;
        }

        main {
            padding: 2em;
        }

        h1 {
            color: #333;
        }

        p {
            font-size: 1.2em;
            line-height: 1.6em;
            margin-bottom: 2em;
        }

        img {
            max-width: 100%;
            height: auto;
            margin-bottom: 2em;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #333;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            font-weight: bold;
            transition: background-color 0.3s;
        }

        a:hover {
            background-color: #555;
        }
    </style>
</head>
<body>

    <header>
        <h1>Página Inicial</h1>
    </header>

    <main>
        <h1> Controle Financeiro </h1>

        <p>O controle financeiro é fundamental para profissionais autônomos se organizarem melhor. Ao registrar suas entradas e saídas, é possível ter uma visão clara das finanças, facilitando o planejamento e a tomada de decisões.</p>

        <p>Clique no botão abaixo para começar a gerenciar suas finanças de forma eficiente!</p>

        <a href="notas/">Login</a>

        
    </main>

</body>
</html>

despesas/main/templates/main/saidas.html
{% extends "main/base.html" %}

{% block title %} Lista de Saídas {% endblock %}

{% block content %}
    <h1 class="mb-4">Saídas</h1>

    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center bg-secondary text-white">
            <h2 class="mb-0">Nova Saída</h2>
        </div>
        <div class="card-body">
            <form method="POST" action="#">
                {% csrf_token %}
                {% for saida in lista.saida_set.all %}
                    {% include "main/movimento_form.html" with movimento=saida %}
                {% endfor %}

                <!-- Adicionar Saída -->
                {% include "main/movimento_form.html" with movimento=None %}

                <!-- Salvar -->
                <button type="submit" name="save" value="save" class="btn btn-dark">
                    Salvar
                </button>
            </form>
        </div>
    </div>
{% endblock %}

despesas/main/templates/main/view.html
{% extends "main/base.html" %}

{% block title %} Histórico Financeiro {% endblock %}

{% block content %}
    <h1 class="mb-4">Histórico Financeiro</h1>

     <!-- Filtro por Mês e Ano -->
<!-- main/view.html -->
<form id="filtroForm" method="GET" action="{% url 'view' %}" class="form-inline mb-2">
    <div class="form-group mr-2">
        {{ filtro_form.mes }}
    </div>
    <div class="form-group mr-2">
        {{ filtro_form.ano }}
    </div>
    <button type="submit" class="btn btn-secondary mr-2">Filtrar</button>
    <button type="button" class="btn btn-dark" onclick="limparFiltro()">Limpar</button>
</form>

<script>
    function limparFiltro() {
        // Define os valores dos campos de filtro para vazio
        document.getElementById('id_mes').value = '';
        document.getElementById('id_ano').value = '';
        
        // Submeter o formulário após redefinir para mostrar todos os dados
        document.getElementById('filtroForm').submit();
    }
</script>


    <!-- Tabela para Entradas -->
    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center bg-secondary text-white">
            <h2 class="mb-0">Entradas</h2>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>Descrição</th>
                        <th>Data</th>
                        <th>Valor</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entrada in entradas %}
                        <tr>
                            <td>{{ entrada.descricao }}</td>
                            <td>{{ entrada.data }}</td>
                            <td>{{ entrada.valor }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            <p class="font-weight-bold">Total de Entradas: {{ total_entradas }}</p>
        </div>
    </div>

    <!-- Tabela para Saídas -->
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center bg-secondary text-white">
            <h2 class="mb-0">Saídas</h2>
        </div>
        <div class="card-body">
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>Descrição</th>
                        <th>Data</th>
                        <th>Valor</th>
                    </tr>
                </thead>
                <tbody>
                    {% for saida in saidas %}
                        <tr>
                            <td>{{ saida.descricao }}</td>
                            <td>{{ saida.data }}</td>
                            <td>{{ saida.valor }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer text-muted">
            <p class="font-weight-bold">Total de Saídas: {{ total_saidas }}</p>
        </div>
    </div>
{% endblock %}

despesas/register/templates/register/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Register</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .login {
            width: 50%;
            height: 50%;
            /* Centralizar na vertical e na horizontal */
            position: absolute;
            top: 5%;
            left: 25%;
        }
    </style>
</head>

{% load crispy_forms_tags %}

<body class="container">
    <div class="login">
        <h3 class="title text-center">Create account</h3>
        <form method="POST" class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Create</button>
        </form>
    </div>
</body>
</html>